name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.BUTLER_ORACLE_SSH }}
      - name: SSH to server
        run: sudo ssh -o StrictHostKeyChecking=no ubuntu@<152.69.160.21>
      - name: display files
        run: ls
      - name: pull repo
        run: git pull
      - name: Install deps
        run: yarn
