name: Node.js CI

on:
  push:
    branches: [ "master" ]
    pull_request: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.BUTLER_ORACLE_SSH }}
      - name: Deploy to Oracle Cloud
        run: ssh -o StrictHostKeyChecking=no ubuntu@<152.69.160.215> << 'EOF'
        run: git pull
        run: yarn start
