name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.BUTLER_ORACLE_SSH }}
      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 152.69.160.215 >> ~/.ssh/known_hosts
          echo "${{ secrets.BUTLER_ORACLE_SSH }}" > ~/.ssh/id_rsa
      - name: Kill Previous Process
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@152.69.160.215 <<EOF
            PID=$(ps aux | grep '[y]arn start' | awk '{print $2}')
            if [ ! -z "$PID" ]; then
              echo "Killing process $PID"
              kill -9 $PID
            else
              echo "No process killed..."
            fi
          EOF
      - name: Pull changes, install deps and deploy.
        timeout-minutes: 1
        run: |
          ssh -tt -o StrictHostKeyChecking=no ubuntu@152.69.160.215 <<EOF
            cd ~ 
            git pull 
            yarn 
            sudo nohup yarn start &
            disown 
          EOF

