name: Node.js CI
# before I forget.. if the 'Kill previous process' task hangs due to a non-successful kill command,
# I should swap out the &&'s for ;'s which will execute the next line despite the previous line not getting a success.
# If that doesn't work, try (command1 &) ; (command2 &), with a wait at the end to wait for these processes.

#TODO: make a function that concatenates asynchronous .sh commands by reading an array from config files (file for each name: step). 
#      Make a function that wraps concatenated commands in SSH and EOF.
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.BUTLER_ORACLE_SSH }}
      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.SERVER_IP }}
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          echo "${{ secrets.BUTLER_ORACLE_SSH }}" > ~/.ssh/id_rsa
      - name: Kill Previous Process
        timeout-minutes: 1
        run: |
          echo ${{ secrets.SERVER_IP }}
          ssh -tt -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} <<'EOF'
            PIDS=$(pgrep -f 'yarn start|yarn.js start|main.js' | tr '\n' ' ') &&
            echo "Found PIDs: $PIDS" &&
            if [ -n "$PIDS" ]; then
              echo "Killing process(es): $PIDS" &&
              for PID in $PIDS; do
                sudo kill -9 $PID &&
                echo "PID $PID killed..."
              done
            else
              echo "No process killed..."
            fi &&
            wait &&
            echo "exiting...." &&
            exit 0
          EOF
      - name: Pull changes, install deps and deploy.
        timeout-minutes: 1
        run: |
          ssh -tt -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} <<'EOF'
            cd ~ 
            git pull 
            yarn 
            sudo nohup yarn start > output.log 2>&1 &
            disown 
            exit 0
          EOF

