name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.BUTLER_ORACLE_SSH }}
      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 152.69.160.215 >> ~/.ssh/known_hosts
          echo "${{ secrets.BUTLER_ORACLE_SSH }}" > ~/.ssh/id_rsa
      - name: Kill Previous Process
        timeout-minutes: 1
        run: |
          ssh -tt -o StrictHostKeyChecking=no ubuntu@152.69.160.215 <<'EOF'
            # Capture PIDs of interest
            PIDS=$(pgrep -f 'yarn start|yarn.js start|main.js')
            echo "Found PIDs: $PIDS"

            if [ -n "$PIDS" ]; then
              for PID in $PIDS; do
                CHILD_PIDS=$(pgrep -P $PID)
                for CHILD_PID in $CHILD_PIDS; do
                  echo "Killing child process $CHILD_PID"
                  sudo kill $CHILD_PID
                  sleep 1  # Ensure command execution
                done
                echo "Killing parent process $PID"
                sudo kill $PID
                sleep 1  # Ensure command execution
              done
            else
              echo "No process killed..."
            fi

            # Ensure processes are terminated
            echo "Sleeping for 5 seconds to allow termination..."
            sleep 5

            # Check remaining processes
            echo "Check remaining processes:"
            ps aux | grep -E '[y]arn|yarn.js|main.js'

            exit 0
          EOF
      - name: Pull changes, install deps and deploy.
        timeout-minutes: 1
        run: |
          ssh -tt -o StrictHostKeyChecking=no ubuntu@152.69.160.215 <<'EOF'
            cd ~ 
            git pull 
            yarn 
            sudo nohup yarn start > output.log 2>&1 &
            disown 
            exit 0
          EOF

