name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.BUTLER_ORACLE_SSH }}
          run: |
            sudo ssh -tt -o StrictHostKeyChecking=no ubuntu@152.69.160.215
            git pull
            yarn
